apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: nicolajh/swj-notification
          env:
            - name: URL_AUTHENTICATIONSERVICE
              value: http://authentication-service:3000
            - name: RABBITURL
              value: rabbitmq-service:5672
            - name: EMAIL
              valueFrom:
                configMapKeyRef:
                  name: gmail
                  key: EMAIL
            - name: EMAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: gmail
                  key: EMAIL_PASSWORD